from enum import StrEnum

class Category(StrEnum):
    WOMEN = "Женщинам"
    MEN = "Мужчинам"
    SHOES = "Обувь"
    KIDS = "Детям"
    HOME = "Дом"
    NEW_YEAR = "Новый год"
    BEAUTY = "Красота"
    ACCESSORIES = "Аксессуары"
    ELECTRONICS = "Электроника"
    TOYS = "Игрушки"
    FURNITURE = "Мебель"
    ADULT = "Товары для взрослых"
    APPLIANCES = "Бытовая техника"
    PETS = "Зоотовары"
    SPORTS = "Спорт"
    AUTO = "Автотовары"
    JEWELRY = "Ювелирные изделия"
    REPAIR = "Для ремонта"
    GARDEN = "Сад и дача"
    HEALTH = "Здоровье"
    STATIONERY = "Канцтовары"
