# Dockerfile.dev для фронтенда
FROM node:20-alpine

WORKDIR /app

# Копируем package.json и yarn.lock для установки зависимостей
COPY package.json yarn.lock ./

# Устанавливаем зависимости
RUN yarn install --frozen-lockfile

RUN cp .env.${DEVELOPER} .env

# Копируем весь проект
COPY . .

EXPOSE 3000

CMD ["yarn", "start"]


## Stage 1: Build the React app
#FROM node:18-alpine AS build
#WORKDIR /app
#COPY package.json yarn.lock ./
#RUN yarn install --frozen-lockfile
#COPY . .
#RUN yarn build
#
## Stage 2: Serve the build output with Nginx
#FROM nginx:stable-alpine
#COPY --from=build /app/build /usr/share/nginx/html
#EXPOSE 80
#CMD ["nginx", "-g", "daemon off;"]
# Dockerfile.dev