# Dockerfile.env для фронтенда
FROM node:20-alpine

WORKDIR /app

# Копируем package.json и yarn.lock для установки зависимостей
COPY package.json yarn.lock ./

# Устанавливаем зависимости
RUN yarn install --frozen-lockfile

COPY local.env .env

# Копируем весь проект
COPY . .

EXPOSE 3000

CMD ["yarn", "start"]
