# Dockerfile.dev для фронтенда
FROM node:20-alpine

WORKDIR /app

# Копируем package.json и yarn.lock для установки зависимостей
COPY package.json yarn.lock ./

# Устанавливаем зависимости
RUN yarn install --frozen-lockfile --network-timeout 300000

# Копируем весь проект
COPY . .

COPY dasha.env .env

EXPOSE 3000

CMD ["yarn", "start"]
