services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: wb-backend-test
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
    restart: unless-stopped
    env_file: .env
    deploy:
      resources:                       # имитируем реальные ресурсы
        limits:
          cpus: "2"                    # поменяйте под свой прод
          memory: "1g"
    ports:
      - "8080:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ~/upload/:/app/upload/
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: wb-db-test
    env_file: .env
    volumes:
      - pg_test_data:/var/lib/postgresql/data/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "5432:5432"
    restart: unless-stopped

  locust:
    image: locustio/locust
    container_name: wb-loadtest
    volumes:
      - ./tests:/mnt/locust             # сюда положите locustfile.py
    environment:
      LOCUST_HOST: "http://backend:8080"
      TG_INIT_DATA: 'query_id=AAFD3bFLAAAAAEPdsUvn-V-E&user=%7B%22id%22%3A1269947715%2C%22first_name%22%3A%22%D0%B4%D0%B0%D1%88%D0%B0%D0%B0%22%2C%22last_name%22%3A%22%22%2C%22username%22%3A%22daria0028%22%2C%22language_code%22%3A%22ru%22%2C%22allows_write_to_pm%22%3Atrue%2C%22photo_url%22%3A%22https%3A%5C%2F%5C%2Ft.me%5C%2Fi%5C%2Fuserpic%5C%2F320%5C%2Fcs5zk8bSfkahSRq1JwQz_B1lkKRtzYh2bCMMQgideuU.svg%22%7D&auth_date=1753862470&signature=9SYiBi9PH5F8rdbncUn_Lzx6pnUoiOnPkTvx3J12b-l-xMkk2qb7wDWOEnIN9cve1HN56Wld3qtylcRKsuJMCA&hash=669d86577f3286d1dc9c14875877559c7e2699e3c9354e4c3be681f5491c2966'
    depends_on:
      - backend
    ports:
      - "8089:8089"                     # Web-GUI Locust (необязательно)

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49
    container_name: wb-cadvisor
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

volumes:
  pg_test_data:
