services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: wb-backend
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080" ]
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./backend/migrations/versions/:/app/migrations/versions/
      - ./backend/upload/:/app/upload/
    ports:
      - "9090:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: wb-bot
    command: [ "python3", "main.py" ]
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      ENVIRONMENT: local

  db:
    image: postgres:17
    container_name: wb-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: wb-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - "./frontend/public:/app/public"

  notificator:
    build:
      context: ./notificator
      dockerfile: Dockerfile
    command: [ "python3", "main.py" ]
    restart: unless-stopped
    volumes:
      - ./backend/upload/:/app/upload/
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres


volumes:
  postgres_data:
