"""add requirements_agree to product

Revision ID: 02558ec308b0
Revises: 3efa6bd17ed2
Create Date: 2025-04-19 18:25:41.550741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02558ec308b0'
down_revision: Union[str, None] = '3efa6bd17ed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('requirements_agree', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'requirements_agree')
    # ### end Alembic commands ###
