"""button in push

Revision ID: 0529594d5b4c
Revises: d92bc63fb3a6
Create Date: 2025-04-09 18:46:02.052762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0529594d5b4c'
down_revision: Union[str, None] = 'd92bc63fb3a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pushes', sa.Column('button_text', sa.String(), nullable=True))
    op.add_column('pushes', sa.Column('button_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pushes', 'button_link')
    op.drop_column('pushes', 'button_text')
    # ### end Alembic commands ###
