"""add order fields

Revision ID: 0a93cb3baa37
Revises: bb29a51a2a1d
Create Date: 2025-03-18 12:12:37.096190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a93cb3baa37'
down_revision: Union[str, None] = 'bb29a51a2a1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('step', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('search_screenshot_path', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('cart_screenshot_path', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('name', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('bank', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('final_cart_screenshot_path', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('delivery_screenshot_path', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('barcodes_screenshot_path', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('review_screenshot_path', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('receipt_screenshot_path', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('receipt_number', sa.String(), nullable=True))
    op.alter_column('orders', 'card_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('orders', 'screenshot_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('screenshot_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('orders', 'card_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('orders', 'receipt_number')
    op.drop_column('orders', 'receipt_screenshot_path')
    op.drop_column('orders', 'review_screenshot_path')
    op.drop_column('orders', 'barcodes_screenshot_path')
    op.drop_column('orders', 'delivery_screenshot_path')
    op.drop_column('orders', 'final_cart_screenshot_path')
    op.drop_column('orders', 'bank')
    op.drop_column('orders', 'name')
    op.drop_column('orders', 'phone_number')
    op.drop_column('orders', 'cart_screenshot_path')
    op.drop_column('orders', 'search_screenshot_path')
    op.drop_column('orders', 'step')
    # ### end Alembic commands ###
