"""add seller_id to product

Revision ID: 1162a9758bb9
Revises: 0a93cb3baa37
Create Date: 2025-03-22 21:11:11.229631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1162a9758bb9'
down_revision: Union[str, None] = '0a93cb3baa37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('seller_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'orders', 'users', ['seller_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'seller_id')
    # ### end Alembic commands ###
