"""Add default transaction_code

Revision ID: 12b78854be33
Revises: f10f357121c7
Create Date: 2025-07-26 18:07:48.069670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12b78854be33'
down_revision: Union[str, None] = 'f10f357121c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('transaction_code', sa.String(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'transaction_code')
    # ### end Alembic commands ###
