"""add order_date to order

Revision ID: 2be9f53fe60a
Revises: 12b78854be33
Create Date: 2025-08-12 11:01:49.495497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2be9f53fe60a'
down_revision: Union[str, None] = '12b78854be33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_date', sa.DateTime(), server_default=sa.text("'1970-01-01 00:00:00'"), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'order_date')
    # ### end Alembic commands ###
