"""add payment_confirmed status to order

Revision ID: 2dff807c6776
Revises: a1b9fc55f20d
Create Date: 2025-04-30 21:51:10.528330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '2dff807c6776'
down_revision: Union[str, None] = 'a1b9fc55f20d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_search_vector', table_name='products', postgresql_using='gin')
    op.sync_enum_values(
        enum_schema='public',
        enum_name='orderstatus',
        new_values=['CASHBACK_PAID', 'CASHBACK_NOT_PAID', 'CANCELLED', 'PAYMENT_CONFIRMED'],
        affected_columns=[TableReference(table_schema='public', table_name='orders', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='orderstatus',
        new_values=['CASHBACK_PAID', 'CASHBACK_NOT_PAID', 'CANCELLED'],
        affected_columns=[TableReference(table_schema='public', table_name='orders', column_name='status')],
        enum_values_to_rename=[],
    )
    op.create_index('ix_products_search_vector', 'products', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
