"""seller and moderator comments

Revision ID: 31c2d93d3741
Revises: 0529594d5b4c
Create Date: 2025-04-14 14:08:29.689262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31c2d93d3741'
down_revision: Union[str, None] = '0529594d5b4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moderator_reviews', sa.Column('comment_to_seller', sa.String(), nullable=True))
    op.add_column('moderator_reviews', sa.Column('comment_to_moderator', sa.String(), nullable=True))
    op.drop_column('moderator_reviews', 'comment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moderator_reviews', sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('moderator_reviews', 'comment_to_moderator')
    op.drop_column('moderator_reviews', 'comment_to_seller')
    # ### end Alembic commands ###
