"""add userhistory

Revision ID: 34388dd4f699
Revises: c1c4a5d48f37
Create Date: 2025-08-15 13:17:12.337484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34388dd4f699'
down_revision: Union[str, None] = 'c1c4a5d48f37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PRODUCT_CREATE', 'STATUS_CHANGED', 'PRODUCT_CHANGED', 'MODERATION_DONE', 'MODERATION_FAILED', 'ENDED', 'FIRST_STEP_DONE', 'SECOND_STEP_DONE', 'THIRD_STEP_DONE', 'FOURTH_STEP_DONE', 'FIFTH_STEP_DONE', 'SIXTH_STEP_DONE', 'SEVENTH_STEP_DONE', 'CASHBACK_DONE', 'CASHBACK_REJECTED', name='action').create(op.get_bind())
    op.create_table('increasing_balances',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('sum', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_history',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('action', postgresql.ENUM('PRODUCT_CREATE', 'STATUS_CHANGED', 'PRODUCT_CHANGED', 'MODERATION_DONE', 'MODERATION_FAILED', 'ENDED', 'FIRST_STEP_DONE', 'SECOND_STEP_DONE', 'THIRD_STEP_DONE', 'FOURTH_STEP_DONE', 'FIFTH_STEP_DONE', 'SIXTH_STEP_DONE', 'SEVENTH_STEP_DONE', 'CASHBACK_DONE', 'CASHBACK_REJECTED', name='action', create_type=False), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('json_before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('json_after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_history')
    op.drop_table('increasing_balances')
    sa.Enum('PRODUCT_CREATE', 'STATUS_CHANGED', 'PRODUCT_CHANGED', 'MODERATION_DONE', 'MODERATION_FAILED', 'ENDED', 'FIRST_STEP_DONE', 'SECOND_STEP_DONE', 'THIRD_STEP_DONE', 'FOURTH_STEP_DONE', 'FIFTH_STEP_DONE', 'SIXTH_STEP_DONE', 'SEVENTH_STEP_DONE', 'CASHBACK_DONE', 'CASHBACK_REJECTED', name='action').drop(op.get_bind())
    # ### end Alembic commands ###
