"""add NOT_PAID status to product

Revision ID: 3efa6bd17ed2
Revises: 5ed63303b433
Create Date: 2025-04-19 14:30:56.914236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '3efa6bd17ed2'
down_revision: Union[str, None] = '5ed63303b433'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='productstatus',
        new_values=['CREATED', 'ACTIVE', 'NOT_PAID', 'DISABLED', 'REJECTED', 'ARCHIVED'],
        affected_columns=[TableReference(table_schema='public', table_name='moderator_reviews', column_name='status_after'), TableReference(table_schema='public', table_name='moderator_reviews', column_name='status_before'), TableReference(table_schema='public', table_name='products', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='productstatus',
        new_values=['CREATED', 'ACTIVE', 'DISABLED', 'REJECTED', 'ARCHIVED'],
        affected_columns=[TableReference(table_schema='public', table_name='moderator_reviews', column_name='status_after'), TableReference(table_schema='public', table_name='moderator_reviews', column_name='status_before'), TableReference(table_schema='public', table_name='products', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
