"""add paid_at

Revision ID: 4093e7264ce2
Revises: e387c6b49b6b
Create Date: 2025-10-14 11:28:07.179651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4093e7264ce2'
down_revision: Union[str, None] = 'e387c6b49b6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('paid_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'paid_at')
    # ### end Alembic commands ###
