"""add order status

Revision ID: 593273b8aae3
Revises: 822f4dc31b66
Create Date: 2025-03-30 20:21:37.221964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '593273b8aae3'
down_revision: Union[str, None] = '822f4dc31b66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('CASHBACK_PAID', 'CASHBACK_NOT_PAID', 'CANCELLED', name='orderstatus').create(op.get_bind())
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('CASHBACK_PAID', 'CASHBACK_NOT_PAID', 'CANCELLED', name='orderstatus'),
               existing_nullable=False,
               postgresql_using='status::orderstatus')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'status',
               existing_type=sa.Enum('CASHBACK_PAID', 'CASHBACK_NOT_PAID', 'CANCELLED', name='orderstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    sa.Enum('CASHBACK_PAID', 'CASHBACK_NOT_PAID', 'CANCELLED', name='orderstatus').drop(op.get_bind())
    # ### end Alembic commands ###
