"""add remaining_products to product

Revision ID: 5ed63303b433
Revises: 9a0fc27b72fb
Create Date: 2025-04-19 12:17:00.606425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ed63303b433'
down_revision: Union[str, None] = '9a0fc27b72fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('remaining_products', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'remaining_products')
    # ### end Alembic commands ###
