"""add user_history

Revision ID: 723de209b9ec
Revises: 34388dd4f699
Create Date: 2025-08-15 16:32:26.310106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '723de209b9ec'
down_revision: Union[str, None] = '34388dd4f699'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_history', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'user_history', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_history', type_='foreignkey')
    op.drop_column('user_history', 'user_id')
    # ### end Alembic commands ###
