"""add status cashback_rejected to order

Revision ID: 869934309960
Revises: 2be9f53fe60a
Create Date: 2025-08-12 13:58:41.291134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '869934309960'
down_revision: Union[str, None] = '2be9f53fe60a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='orderstatus',
        new_values=['CASHBACK_PAID', 'CASHBACK_NOT_PAID', 'CANCELLED', 'PAYMENT_CONFIRMED', 'CASHBACK_REJECTED'],
        affected_columns=[TableReference(table_schema='public', table_name='orders', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='orderstatus',
        new_values=['CASHBACK_PAID', 'CASHBACK_NOT_PAID', 'CANCELLED', 'PAYMENT_CONFIRMED'],
        affected_columns=[TableReference(table_schema='public', table_name='orders', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
