"""add on_delete cascade

Revision ID: 86eae895a921
Revises: 44d88de62970
Create Date: 2025-08-21 19:49:49.940987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86eae895a921'
down_revision: Union[str, None] = '44d88de62970'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('reviews_product_id_fkey', 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_history_product_id_fkey', 'user_history', type_='foreignkey')
    op.create_foreign_key(None, 'user_history', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_history', type_='foreignkey')
    op.create_foreign_key('user_history_product_id_fkey', 'user_history', 'products', ['product_id'], ['id'])
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key('reviews_product_id_fkey', 'reviews', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
