"""add cascade delete to ModeratorReview

Revision ID: 96337263fc6b
Revises: c7e3f04589b5
Create Date: 2025-08-21 16:51:58.206546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96337263fc6b'
down_revision: Union[str, None] = 'c7e3f04589b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('moderator_reviews_product_id_fkey'), 'moderator_reviews', type_='foreignkey')
    op.create_foreign_key(None, 'moderator_reviews', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'moderator_reviews', type_='foreignkey')
    op.create_foreign_key(op.f('moderator_reviews_product_id_fkey'), 'moderator_reviews', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
