"""add user has_discount and referrer_bonus

Revision ID: 9a0fc27b72fb
Revises: 31c2d93d3741
Create Date: 2025-04-16 14:25:34.869373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a0fc27b72fb'
down_revision: Union[str, None] = '31c2d93d3741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('invited_by', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('has_discount', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('referrer_bonus', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['invited_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'referrer_bonus')
    op.drop_column('users', 'has_discount')
    op.drop_column('users', 'invited_by')
    # ### end Alembic commands ###
