"""add fields on Product

Revision ID: bb29a51a2a1d
Revises: a29a95397ff4
Create Date: 2025-03-16 16:53:18.159601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb29a51a2a1d'
down_revision: Union[str, None] = 'a29a95397ff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('AFTER_REVIEW', 'AFTER_DELIVERY', 'ON_15TH_DAY', name='payouttime').create(op.get_bind())
    sa.Enum('WOMEN', 'MEN', 'SHOES', 'KIDS', 'HOME', 'NEW_YEAR', 'BEAUTY', 'ACCESSORIES', 'ELECTRONICS', 'TOYS', 'FURNITURE', 'ADULT', 'APPLIANCES', 'PETS', 'SPORTS', 'AUTO', 'JEWELRY', 'REPAIR', 'GARDEN', 'HEALTH', 'STATIONERY', name='category').create(op.get_bind())
    op.add_column('products', sa.Column('brand', sa.String(), nullable=False))
    op.add_column('products', sa.Column('category', postgresql.ENUM('WOMEN', 'MEN', 'SHOES', 'KIDS', 'HOME', 'NEW_YEAR', 'BEAUTY', 'ACCESSORIES', 'ELECTRONICS', 'TOYS', 'FURNITURE', 'ADULT', 'APPLIANCES', 'PETS', 'SPORTS', 'AUTO', 'JEWELRY', 'REPAIR', 'GARDEN', 'HEALTH', 'STATIONERY', name='category', create_type=False), nullable=False))
    op.add_column('products', sa.Column('key_word', sa.String(), nullable=False))
    op.add_column('products', sa.Column('general_repurchases', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('daily_repurchases', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('wb_price', sa.Float(), nullable=False))
    op.add_column('products', sa.Column('tg', sa.String(), nullable=False))
    op.add_column('products', sa.Column('payment_time', postgresql.ENUM('AFTER_REVIEW', 'AFTER_DELIVERY', 'ON_15TH_DAY', name='payouttime', create_type=False), nullable=False))
    op.add_column('products', sa.Column('review_requirements', sa.String(), nullable=False))
    op.drop_column('products', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('products', 'review_requirements')
    op.drop_column('products', 'payment_time')
    op.drop_column('products', 'tg')
    op.drop_column('products', 'wb_price')
    op.drop_column('products', 'daily_repurchases')
    op.drop_column('products', 'general_repurchases')
    op.drop_column('products', 'key_word')
    op.drop_column('products', 'category')
    op.drop_column('products', 'brand')
    sa.Enum('WOMEN', 'MEN', 'SHOES', 'KIDS', 'HOME', 'NEW_YEAR', 'BEAUTY', 'ACCESSORIES', 'ELECTRONICS', 'TOYS', 'FURNITURE', 'ADULT', 'APPLIANCES', 'PETS', 'SPORTS', 'AUTO', 'JEWELRY', 'REPAIR', 'GARDEN', 'HEALTH', 'STATIONERY', name='category').drop(op.get_bind())
    sa.Enum('AFTER_REVIEW', 'AFTER_DELIVERY', 'ON_15TH_DAY', name='payouttime').drop(op.get_bind())
    # ### end Alembic commands ###
