"""add product status

Revision ID: bc9b6854928e
Revises: 1162a9758bb9
Create Date: 2025-03-25 22:21:38.563697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc9b6854928e'
down_revision: Union[str, None] = '1162a9758bb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('CREATED', 'ACTIVE', 'DISABLED', 'REJECTED', 'ARCHIVED', name='productstatus').create(op.get_bind())
    op.add_column('products', sa.Column('status', postgresql.ENUM('CREATED', 'ACTIVE', 'DISABLED', 'REJECTED', 'ARCHIVED', name='productstatus', create_type=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'status')
    sa.Enum('CREATED', 'ACTIVE', 'DISABLED', 'REJECTED', 'ARCHIVED', name='productstatus').drop(op.get_bind())
    # ### end Alembic commands ###
