"""remove daily_repurchases

Revision ID: c1c4a5d48f37
Revises: 869934309960
Create Date: 2025-08-12 17:38:40.724458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1c4a5d48f37'
down_revision: Union[str, None] = '869934309960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'daily_repurchases')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('daily_repurchases', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
