"""add rating to SellerReview

Revision ID: c6011261105b
Revises: 4093e7264ce2
Create Date: 2025-10-21 19:57:27.315486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6011261105b'
down_revision: Union[str, None] = '4093e7264ce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller_reviews', sa.Column('rating', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seller_reviews', 'rating')
    # ### end Alembic commands ###
