"""add agree_terms to user_history

Revision ID: c87416833552
Revises: 723de209b9ec
Create Date: 2025-08-17 00:02:27.289672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'c87416833552'
down_revision: Union[str, None] = '723de209b9ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='action',
        new_values=['PRODUCT_CREATE', 'STATUS_CHANGED', 'PRODUCT_CHANGED', 'MODERATION_DONE', 'MODERATION_FAILED', 'ENDED', 'AGREE_TERMS', 'FIRST_STEP_DONE', 'SECOND_STEP_DONE', 'THIRD_STEP_DONE', 'FOURTH_STEP_DONE', 'FIFTH_STEP_DONE', 'SIXTH_STEP_DONE', 'SEVENTH_STEP_DONE', 'CASHBACK_DONE', 'CASHBACK_REJECTED'],
        affected_columns=[TableReference(table_schema='public', table_name='user_history', column_name='action')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='action',
        new_values=['PRODUCT_CREATE', 'STATUS_CHANGED', 'PRODUCT_CHANGED', 'MODERATION_DONE', 'MODERATION_FAILED', 'ENDED', 'FIRST_STEP_DONE', 'SECOND_STEP_DONE', 'THIRD_STEP_DONE', 'FOURTH_STEP_DONE', 'FIFTH_STEP_DONE', 'SIXTH_STEP_DONE', 'SEVENTH_STEP_DONE', 'CASHBACK_DONE', 'CASHBACK_REJECTED'],
        affected_columns=[TableReference(table_schema='public', table_name='user_history', column_name='action')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
