"""push soft deletion

Revision ID: d92bc63fb3a6
Revises: 909dc0adb8a2
Create Date: 2025-04-09 18:29:57.869011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'd92bc63fb3a6'
down_revision: Union[str, None] = '909dc0adb8a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pushes', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.sync_enum_values(
        enum_schema='public',
        enum_name='userrole',
        new_values=['USER', 'CLIENT', 'SELLER', 'MODERATOR', 'ADMIN'],
        affected_columns=[TableReference(table_schema='public', table_name='users', column_name='role')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='userrole',
        new_values=['USER', 'MODERATOR', 'ADMIN'],
        affected_columns=[TableReference(table_schema='public', table_name='users', column_name='role')],
        enum_values_to_rename=[],
    )
    op.drop_column('pushes', 'deleted_at')
    # ### end Alembic commands ###
