"""fix product status enum

Revision ID: dcd8d88a3066
Revises: 77f5ca11e091
Create Date: 2025-03-29 19:20:44.915139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'dcd8d88a3066'
down_revision: Union[str, None] = '77f5ca11e091'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='productstatus',
        new_values=['CREATED', 'ACTIVE', 'DISABLED', 'REJECTED', 'ARCHIVED'],
        affected_columns=[TableReference(table_schema='public', table_name='moderator_reviews', column_name='status_after'), TableReference(table_schema='public', table_name='moderator_reviews', column_name='status_before'), TableReference(table_schema='public', table_name='products', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='productstatus',
        new_values=['CREATED', 'ACTIVE', 'DISABLED'],
        affected_columns=[TableReference(table_schema='public', table_name='moderator_reviews', column_name='status_after'), TableReference(table_schema='public', table_name='moderator_reviews', column_name='status_before'), TableReference(table_schema='public', table_name='products', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
