"""add REMINDER_SENT to order status

Revision ID: e387c6b49b6b
Revises: 093cca036309
Create Date: 2025-08-31 13:10:11.894046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'e387c6b49b6b'
down_revision: Union[str, None] = '093cca036309'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='orderstatus',
        new_values=['CASHBACK_PAID', 'CASHBACK_NOT_PAID', 'CANCELLED', 'PAYMENT_CONFIRMED', 'CASHBACK_REJECTED', 'REMINDER_SENT'],
        affected_columns=[TableReference(table_schema='public', table_name='orders', column_name='status')],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='action',
        new_values=['PRODUCT_CREATE', 'STATUS_CHANGED', 'PRODUCT_CHANGED', 'MODERATION_DONE', 'MODERATION_FAILED', 'ENDED', 'AGREE_TERMS', 'FIRST_STEP_DONE', 'SECOND_STEP_DONE', 'THIRD_STEP_DONE', 'FOURTH_STEP_DONE', 'FIFTH_STEP_DONE', 'SIXTH_STEP_DONE', 'SEVENTH_STEP_DONE', 'CASHBACK_DONE', 'CASHBACK_REJECTED', 'REMINDER_SENT'],
        affected_columns=[TableReference(table_schema='public', table_name='user_history', column_name='action')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='action',
        new_values=['PRODUCT_CREATE', 'STATUS_CHANGED', 'PRODUCT_CHANGED', 'MODERATION_DONE', 'MODERATION_FAILED', 'ENDED', 'AGREE_TERMS', 'FIRST_STEP_DONE', 'SECOND_STEP_DONE', 'THIRD_STEP_DONE', 'FOURTH_STEP_DONE', 'FIFTH_STEP_DONE', 'SIXTH_STEP_DONE', 'SEVENTH_STEP_DONE', 'CASHBACK_DONE', 'CASHBACK_REJECTED'],
        affected_columns=[TableReference(table_schema='public', table_name='user_history', column_name='action')],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='orderstatus',
        new_values=['CASHBACK_PAID', 'CASHBACK_NOT_PAID', 'CANCELLED', 'PAYMENT_CONFIRMED', 'CASHBACK_REJECTED'],
        affected_columns=[TableReference(table_schema='public', table_name='orders', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
