name: DEPLOY


on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  deploy:
    name: Deploy all
    runs-on: [
      "self-hosted",
      "dev"
    ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare Env
        run: |
          touch .env
          
          echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" >> .env

      - name: Compose up
        run: |
          sudo docker compose stop
          sudo docker compose up --build -d

      - name: Cleanup
        run: |
          docker system prune -a -f
