name: DEPLOY


on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  deploy:
    name: Deploy all
    runs-on: [
      "self-hosted",
      "dev"
    ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare Env
        run: |
          touch .env

          echo "POSTGRES_USER=postgres" >> .env
          echo "POSTGRES_PASSWORD=postgres" >> .env

          echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" >> .env
          echo "BOT_USERNAME=cashbackwb_ru_bot" >> .env
          echo "BOT_CHANNEL_ID=-1001206912181" >> .env
          echo "BOT_PAID_TOPIC_ID=13" >> .env
          echo "BOT_FREE_TOPIC_ID=1151" >> .env

      - name: Compose up
        run: |
          sudo docker compose stop
          sudo docker compose up --build -d

      - name: Cleanup
        run: |
          docker system prune -a -f
